<p><h1>Adding new user</h1></p>

<form name="main">
    E-mail:<br>
    <input type="text" name="email" size="15" maxlength="30"><br>
    Password:<br>
    <input type="password" name="password" size="15" maxlength="30"><br>
    First name:<br>
    <input type="text" name="email" size="15" maxlength="20"><br>
    Last name:<br>
    <input type="text" name="email" size="15" maxlength="20"><br>
</form>
