<?php
/**
 * @var Model_User $user
 */
//$user = $view->getParam('user');
?>

<?php //if($user) : ?>
<table border="2px">
    <th>Id</th>
    <th>Name</th>
    <th>Email</th>
    <tr>
        <td><?php echo 'Peas'; ?></td>
        <td><?php echo 'of'; ?></td>
        <td><?php echo 'shit'; ?></td>
    </tr>
</table>

<?php // elseif($view->getParam('error')) : ?>
<!--    <div class="error">--><?php //echo $view->getParam('error')?><!--</div>-->
<?php //endif; ?>