<p><h1>Admin path</h1></p>
<table border="2px">
    <tr>
        <td><input type="submit" class="global_actions" name="users" value="Users" onclick="javascript:window.location='/admin/users'"/></td>
        <td><input type="submit" class="global_actions" name="products" value="Products" onclick="javascript:window.location='/admin/products'"/></td>
        <td><input type="submit" class="global_actions" name="orders" value="Orders" onclick="javascript:window.location='/admin/orders'"/></td>
    </tr>
</table>
