<?php
/**
 * @var Model_User $user
 */
$users = $view->getParam('user');

?>

<?php if($users) : ?>
    <p><h1>Users</h1></p>
    <p><input type="submit" class="global_actions" name="add_user" value="Add new user" onclick="javascript:window.location='/admin/addinguserpage';"/></p>
    <table border="2px">
        <th>Id</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Year of Birth</th>
        <th>Email</th>
        <th>Role ID</th>
        <th>Skills</th>
        <th>Actions</th>

        <?php foreach ($users as $user)
        { ?>
            <tr>
                <td><?php echo $user->id; ?></td>
                <td><?php echo $user->first_name; ?></td>
                <td><?php echo $user->last_name; ?></td>
                <td><?php echo $user->birth; ?></td>
                <td><?php echo $user->email; ?></td>
                <td><?php echo $user->role_id; ?></td>
                <td><?php echo $user->skills; ?></td>
                <td> <input type="submit" name="edit_user" value="Edit" onclick="javascript:window.location='/admin/editinguserpage/<?php echo $user->id; ?>';"/>
                     <input type="submit" name="delete" value="Delete" onclick="javascript: deleting(<?php echo $user->id; ?>);"/>
                </td>
            </tr>
        <?php } ?>
    </table>

<?php  elseif($view->getParam('error')) : ?>
    <div class="error"><?php echo $view->getParam('error')?></div>
<?php endif; ?>