<?php 
    $userId = $controller->getUserId(); 
    
    $userRoleId = 0;
    if($userId) {
        $userModel      = Model_User::getById($userId);
        $userEmail      = $userModel->email;
        $userRoleId     = $userModel->role_id; 
    }
?>

<html>
    <head>
        <title>Project</title>
        <link rel="stylesheet" type="text/css" href="/css/style.css" />
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>        
        <!--<script type="text/javascript" src="/js/jquery.js"></script>-->
        <script type="text/javascript" src="/js/authorize.js?333"></script>
        <script type="text/javascript" src="/js/actionhelper.js"></script>
       
        
    </head>    
    <body>  
        <div id="error"><?php //echo !empty($errorMessage) ? $errorMessage : ''; ?></div>

        <div id="userEmail"><?php echo !empty($userId) ? 'You sign in as: ' : '';?><a href="<?php echo !empty($userId)? '/user/profile/id/'.$userId : '';?>"><?php echo !empty($userEmail) ? $userEmail : ''; ?></a></div>
        <div id="userId"><a id="logout" href="#"><?php echo !empty($userId) ? 'Exit' : ''?></a></div>

        <div id="loginFormDiv" <?php if(!empty($userId)) { echo 'class = "hide"'; } ?> >
            <form name="authorize" id="loginForm" method="POST" autocomplete="off">
                <input placeholder="Email" type="text" name="email" maxlength="20" /><br />
                <input placeholder="Password" type="password" name="password" maxlength="30" /><br />
                <input id="save_checkbox" type="checkbox" name="save" value="1" /><label for="save_checkbox">Save</label><br />
                <input type="submit" name="login" value="Enter" />
                <input type="submit" name="register" value="Register" />
            </form>
        </div>
           <div id="menu">
                <a href="/">Main page </a> &nbsp&nbsp | &nbsp&nbsp
                <a href="/product/index">Products </a>  &nbsp&nbsp | &nbsp&nbsp
                <a href="/company/portfolio">Portfolio </a>  &nbsp&nbsp | &nbsp&nbsp
                <a href="/company/about">About company </a>  &nbsp&nbsp | &nbsp&nbsp
                <a href="/company/contact">Contacts </a>  &nbsp&nbsp | &nbsp&nbsp
                <?php //if ($userRoleId == Model_User::ROLE_ADMIN) : ?>
                    <a id="admin_href" href="/admin/index" <?php if($userRoleId != Model_User::ROLE_ADMIN) { echo 'class="hide"'; } ?>>Admin path </a>  &nbsp&nbsp
                <?php //endif; ?>
            </div>
        <br />
        <hr />

    <?php
        
   
    if(file_exists($viewFileName)) {
        include $viewFileName;
    }
    ?>
        
    <hr />    
    <div>Your advertising may be here</div>

    </body>
    
</html>